export const CHAT_CHANGE_STATE = 'CHAT_CHANGE_STATE';

export const GET_USER_BY_NAME = 'GET_USER_BY_NAME';
export const GET_USER_BY_NAME_SUCCESS = 'GET_USER_BY_NAME_SUCCESS';
export const GET_USER_BY_NAME_FAILURE = 'GET_USER_BY_NAME_FAILURE';
