export const CHAT_CHANGE_STATE = 'CHAT_CHANGE_STATE';

export const GET_USER_BY_NAME = 'GET_USER_BY_NAME';
export const GET_USER_BY_NAME_SUCCESS = 'GET_USER_BY_NAME_SUCCESS';
export const GET_USER_BY_NAME_FAILURE = 'GET_USER_BY_NAME_FAILURE';

export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';

export const MARK_UNREAD = 'MARK_UNREAD';
export const ADD_UNREAD = 'ADD_UNREAD';
export const MARK_READ = 'MARK_READ';
