export const GET_FRIEND = 'GET_FRIEND';
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS';
export const GET_FRIEND_FAIL = 'GET_FRIEND_FAIL';

export const FRIEND_CHANGE_STATE = 'FRIEND_CHANGE_STATE';
