export const GET_ME = 'GET_ME';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const UPDATE_ME_FAILURE = 'UPDATE_ME_FAILURE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const GET_POST_PROFILE = 'GET_POST_ME';
export const GET_POST_PROFILE_SUCCESS = 'GET_POST_ME_SUCCESS';

export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';

export const PROFILE_CHANGE_STATE = 'PROFILE_CHANGE_STATE';
