export const OPEN_MODAL_POST = 'OPEN_MODAL_POST';
export const MODAL_CREATE_POST = 'MODAL_CREATE_POST';

export const MODAL_UPDATE_POST = 'MODAL_UPDATE_POST';

export const OPEN_MODAL_POST_IMG = 'OPEN_MODAL_POST_IMG';
export const MODAL_CREATE_POST_IMG = 'MODAL_CREATE_POST_IMG';
export const CLOSE_IMG_CMT = 'CLOSE_IMG_CMT';
export const CLOSE_MODAL_POST = 'CLOSE_MODAL_POST';
