export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const NOTIFICATION_CHANGE_STATE = 'NOTIFICATION_CHANGE_STATE';

export const MARK_READ_NOTIFICATION = 'MARK_READ_NOTIFICATION';
export const MARK_READ_ALL = 'MARK_READ_ALL';
