export const RECHARGE_MONEY = 'RECHARGE_MONEY';
export const RECHARGE_MONEY_SUCCESS = 'RECHARGE_MONEY_SUCCESS';
export const WALLET_CHANGE_STATE = 'WALLET_CHANGE_STATE';

export const WALLET_TRANSFER = 'WALLET_TRANSFER';
export const WALLET_TRANSFER_SUCCESS = 'WALLET_TRANSFER_SUCCESS';
