export const RECHARGE_MONEY = 'RECHARGE_MONEY';
<<<<<<< HEAD
export const WITHDRAW_MONEY = 'WITHDRAW_MONEY';
=======
export const RECHARGE_MONEY_SUCCESS = 'RECHARGE_MONEY_SUCCESS';
export const WALLET_CHANGE_STATE = 'WALLET_CHANGE_STATE';
>>>>>>> 38f489d66aad9839e3c3a580f7a790d01e95c93a
